<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-09-12 14:56

$extensionPath = t3lib_extMgm::extPath('cabag_extbase');
$classes = array(
	'tx_cabagextbase_controller_basecontroller' => $extensionPath . 'Classes/Controller/BaseController.php',
	'tx_cabagextbase_domain_model_staticcountry' => $extensionPath . 'Classes/Domain/Model/StaticCountry.php',
	'tx_cabagextbase_domain_model_staticcountryzone' => $extensionPath . 'Classes/Domain/Model/StaticCountryZone.php',
	'tx_cabagextbase_domain_model_staticlanguage' => $extensionPath . 'Classes/Domain/Model/StaticLanguage.php',
	'tx_cabagextbase_domain_repository_staticcountryrepository' => $extensionPath . 'Classes/Domain/Repository/StaticCountryRepository.php',
	'tx_cabagextbase_domain_repository_staticcountryzonerepository' => $extensionPath . 'Classes/Domain/Repository/StaticCountryZoneRepository.php',
	'tx_cabagextbase_domain_repository_staticlanguagerepository' => $extensionPath . 'Classes/Domain/Repository/StaticLanguageRepository.php',
	'tx_cabagextbase_object_manager' => $extensionPath . 'Classes/Object/Manager.php',
	'tx_cabagextbase_persistence_queryfactory' => $extensionPath . 'Classes/Persistence/QueryFactory.php',
	'tx_cabagextbase_persistence_repository' => $extensionPath . 'Classes/Persistence/Repository.php',
	'tx_cabagextbase_persistence_storage_cabagtypo3dbbackend' => $extensionPath . 'Classes/Persistence/Storage/CabagTypo3DbBackend.php',
	'tx_cabagextbase_utility_abstractwizicon' => $extensionPath . 'Classes/Utility/AbstractWizicon.php',
	'tx_cabagextbase_utility_file' => $extensionPath . 'Classes/Utility/File.php',
	'tx_cabagextbase_utility_logging' => $extensionPath . 'Classes/Utility/Logging.php',
	'tx_cabagextbase_utility_mail' => $extensionPath . 'Classes/Utility/Mail.php',
	'tx_cabagextbase_utility_fixformtoken' => $extensionPath . 'Classes/Utility/FixFormToken.php',
	'tx_cabagextbase_validator_boundnotemptyvalidator' => $extensionPath . 'Classes/Validator/BoundNotEmptyValidator.php',
	'tx_cabagextbase_validator_twicevalidator' => $extensionPath . 'Classes/Validator/TwiceValidator.php',
	'tx_cabagextbase_viewhelpers_cdataviewhelper' => $extensionPath . 'Classes/ViewHelpers/CdataViewHelper.php',
	'tx_cabagextbase_viewhelpers_date2calviewhelper' => $extensionPath . 'Classes/ViewHelpers/Date2CalViewHelper.php',
	'tx_cabagextbase_viewhelpers_datepickerviewhelper' => $extensionPath . 'Classes/ViewHelpers/DatepickerViewHelper.php',
	'tx_cabagextbase_viewhelpers_debugviewhelper' => $extensionPath . 'Classes/ViewHelpers/DebugViewHelper.php',
	'tx_cabagextbase_viewhelpers_escapeviewhelper' => $extensionPath . 'Classes/ViewHelpers/EscapeViewHelper.php',
	'tx_cabagextbase_viewhelpers_formviewhelper' => $extensionPath . 'Classes/ViewHelpers/FormViewHelper.php',
	'tx_cabagextbase_viewhelpers_ifcontainsviewhelper' => $extensionPath . 'Classes/ViewHelpers/IfContainsViewHelper.php',
	'tx_cabagextbase_viewhelpers_iferrorviewhelper' => $extensionPath . 'Classes/ViewHelpers/IfErrorViewHelper.php',
	'tx_cabagextbase_viewhelpers_implodeviewhelper' => $extensionPath . 'Classes/ViewHelpers/ImplodeViewHelper.php',
	'tx_cabagextbase_viewhelpers_jsonviewhelper' => $extensionPath . 'Classes/ViewHelpers/JsonViewHelper.php',
	'tx_cabagextbase_viewhelpers_objectaccessorviewhelper' => $extensionPath . 'Classes/ViewHelpers/ObjectAccessorViewHelper.php',
	'tx_cabagextbase_viewhelpers_pregreplaceviewhelper' => $extensionPath . 'Classes/ViewHelpers/PregReplaceViewHelper.php',
	'tx_cabagextbase_viewhelpers_rawviewhelper' => $extensionPath . 'Classes/ViewHelpers/RawViewHelper.php',
	'tx_cabagextbase_viewhelpers_selectviewhelper' => $extensionPath . 'Classes/ViewHelpers/SelectViewHelper.php',
	'tx_cabagextbase_viewhelpers_strftimeviewhelper' => $extensionPath . 'Classes/ViewHelpers/StrftimeViewHelper.php',
	'tx_cabagextbase_viewhelpers_format_htmlviewhelper' => $extensionPath . 'Classes/ViewHelpers/Format/HtmlViewHelper.php',
	'tx_cabagextbase_viewhelpers_widget_flashuploadviewhelper' => $extensionPath . 'Classes/ViewHelpers/Widget/FlashuploadViewHelper.php',
	'tx_cabagextbase_viewhelpers_widget_controller_flashuploadcontroller' => $extensionPath . 'Classes/ViewHelpers/Widget/Controller/FlashuploadController.php',
	'tx_cabagextbase_eid_flashupload' => $extensionPath . 'Classes/eID/Flashupload.php',
	'tx_cabagextbase_viewhelpers_imagelazyviewhelper' => $extensionPath . 'Classes/ViewHelpers/ImageLazyViewHelper.php',
	'tx_cabagextbase_viewhelpers_link_lightboxviewhelper' => $extensionPath . 'Classes/ViewHelpers/Link/LightboxViewHelper.php',
	'tx_cabagextbase_viewhelpers_iforviewhelper' => $extensionPath . 'Classes/ViewHelpers/IfOrViewHelper.php',
	'tx_cabagextbase_viewhelpers_typolinkhelper' => $extensionPath . 'Classes/ViewHelpers/TypoLinkHelper.php',
);

if (version_compare(TYPO3_version, '6.2', '>=')) {
	$classes['tx_cabagextbase_eid_fixformtoken'] = $extensionPath . 'Classes/eID/FixFormToken.php';
}

return $classes;